name: push main branche

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Deploy auxo database
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACEEESSKEY }}
          aws-region: cn-northwest-1
          role-to-assume: ${{ secrets.AWSROLETOASSUME }}
          role-external-id: ${{ secrets.AWSROLEEXTERNALID }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsSession

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name coloseo

      - name: Install helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install Postgresql
        run: helm upgrade --install --namespace auxo -f values-staging.yaml postgresql postgresql/
